### ISSUE TITLE
Can you give me assistance?

### ISSUE THREAD

**Issue by ElFenomenoTv** [aditya00kumar/document-classification#1]
I`m starting now to learn Document Classification and I need some help, can you help me to explain how it working your Project? What I need to start, to put on html pages? A video with how it works is perfect for me, I think, I wanna make this project to work in other language and is perfect if you show me how to do that. Thx a lot and I appreciate your work.

**Comment by aditya00kumar** [comment]
@FabyOfficial, This project uses some pre-processing function which at this point of time support english language. To make this project to work on other languages, you have to modify
https://github.com/aditya00kumar/document-classification/blob/master/preprocess.py
for pre-processing of text. 
1. stemming
2. lemmatization
3. stop_words - you want to add stop words specific to your language of choice

Other functions are also there, have a look at those weather they are useful for your language. And use only the modified functions which will take of pre-processing task. And use only those functions in
https://github.com/aditya00kumar/document-classification/blob/master/app.py in 
read_process_data(path, files_path) function. Everything else should work fine as it usesTf-idf for feature creation. You don't need to change html as of now.

Hope this help. Video I am not sure at this moment of time.
